// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: dwango/nicolive/chat/data/FingerPrint.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Dwango.Nicolive.Chat.Data {

  /// <summary>Holder for reflection information generated from dwango/nicolive/chat/data/FingerPrint.proto</summary>
  public static partial class FingerPrintReflection {

    #region Descriptor
    /// <summary>File descriptor for dwango/nicolive/chat/data/FingerPrint.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static FingerPrintReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Citkd2FuZ28vbmljb2xpdmUvY2hhdC9kYXRhL0ZpbmdlclByaW50LnByb3Rv",
            "Ehlkd2FuZ28ubmljb2xpdmUuY2hhdC5kYXRhGh5nb29nbGUvcHJvdG9idWYv",
            "ZHVyYXRpb24ucHJvdG8i4wIKC0ZpbmdlclByaW50EkEKCHBvc2l0aW9uGAEg",
            "ASgOMi8uZHdhbmdvLm5pY29saXZlLmNoYXQuZGF0YS5GaW5nZXJQcmludC5Q",
            "b3NpdGlvbhI5CgRzaXplGAIgASgOMisuZHdhbmdvLm5pY29saXZlLmNoYXQu",
            "ZGF0YS5GaW5nZXJQcmludC5TaXplEisKCGR1cmF0aW9uGAQgASgLMhkuZ29v",
            "Z2xlLnByb3RvYnVmLkR1cmF0aW9uIoABCghQb3NpdGlvbhIHCgNvZmYQABIP",
            "CgtoaWRhcmlzaGl0YRABEgkKBXNoaXRhEAISDQoJbWlnaXNoaXRhEAMSCgoG",
            "aGlkYXJpEAQSCAoEbmFrYRAFEggKBG1pZ2kQBhIMCghoaWRhcml1ZRAHEgYK",
            "AnVlEAgSCgoGbWlnaXVlEAkiJgoEU2l6ZRIJCgVzbWFsbBAAEgoKBm1pZGRs",
            "ZRABEgcKA2JpZxACYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Google.Protobuf.WellKnownTypes.DurationReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Dwango.Nicolive.Chat.Data.FingerPrint), global::Dwango.Nicolive.Chat.Data.FingerPrint.Parser, new[]{ "Position", "Size", "Duration" }, null, new[]{ typeof(global::Dwango.Nicolive.Chat.Data.FingerPrint.Types.Position), typeof(global::Dwango.Nicolive.Chat.Data.FingerPrint.Types.Size) }, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class FingerPrint : pb::IMessage<FingerPrint> {
    private static readonly pb::MessageParser<FingerPrint> _parser = new pb::MessageParser<FingerPrint>(() => new FingerPrint());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<FingerPrint> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Dwango.Nicolive.Chat.Data.FingerPrintReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public FingerPrint() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public FingerPrint(FingerPrint other) : this() {
      position_ = other.position_;
      size_ = other.size_;
      duration_ = other.duration_ != null ? other.duration_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public FingerPrint Clone() {
      return new FingerPrint(this);
    }

    /// <summary>Field number for the "position" field.</summary>
    public const int PositionFieldNumber = 1;
    private global::Dwango.Nicolive.Chat.Data.FingerPrint.Types.Position position_ = 0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Dwango.Nicolive.Chat.Data.FingerPrint.Types.Position Position {
      get { return position_; }
      set {
        position_ = value;
      }
    }

    /// <summary>Field number for the "size" field.</summary>
    public const int SizeFieldNumber = 2;
    private global::Dwango.Nicolive.Chat.Data.FingerPrint.Types.Size size_ = 0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Dwango.Nicolive.Chat.Data.FingerPrint.Types.Size Size {
      get { return size_; }
      set {
        size_ = value;
      }
    }

    /// <summary>Field number for the "duration" field.</summary>
    public const int DurationFieldNumber = 4;
    private global::Google.Protobuf.WellKnownTypes.Duration duration_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Google.Protobuf.WellKnownTypes.Duration Duration {
      get { return duration_; }
      set {
        duration_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as FingerPrint);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(FingerPrint other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Position != other.Position) return false;
      if (Size != other.Size) return false;
      if (!object.Equals(Duration, other.Duration)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Position != 0) hash ^= Position.GetHashCode();
      if (Size != 0) hash ^= Size.GetHashCode();
      if (duration_ != null) hash ^= Duration.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Position != 0) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Position);
      }
      if (Size != 0) {
        output.WriteRawTag(16);
        output.WriteEnum((int) Size);
      }
      if (duration_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(Duration);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Position != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Position);
      }
      if (Size != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Size);
      }
      if (duration_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Duration);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(FingerPrint other) {
      if (other == null) {
        return;
      }
      if (other.Position != 0) {
        Position = other.Position;
      }
      if (other.Size != 0) {
        Size = other.Size;
      }
      if (other.duration_ != null) {
        if (duration_ == null) {
          duration_ = new global::Google.Protobuf.WellKnownTypes.Duration();
        }
        Duration.MergeFrom(other.Duration);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            position_ = (global::Dwango.Nicolive.Chat.Data.FingerPrint.Types.Position) input.ReadEnum();
            break;
          }
          case 16: {
            size_ = (global::Dwango.Nicolive.Chat.Data.FingerPrint.Types.Size) input.ReadEnum();
            break;
          }
          case 34: {
            if (duration_ == null) {
              duration_ = new global::Google.Protobuf.WellKnownTypes.Duration();
            }
            input.ReadMessage(duration_);
            break;
          }
        }
      }
    }

    #region Nested types
    /// <summary>Container for nested types declared in the FingerPrint message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static partial class Types {
      public enum Position {
        [pbr::OriginalName("off")] Off = 0,
        [pbr::OriginalName("hidarishita")] Hidarishita = 1,
        [pbr::OriginalName("shita")] Shita = 2,
        [pbr::OriginalName("migishita")] Migishita = 3,
        [pbr::OriginalName("hidari")] Hidari = 4,
        [pbr::OriginalName("naka")] Naka = 5,
        [pbr::OriginalName("migi")] Migi = 6,
        [pbr::OriginalName("hidariue")] Hidariue = 7,
        [pbr::OriginalName("ue")] Ue = 8,
        [pbr::OriginalName("migiue")] Migiue = 9,
      }

      public enum Size {
        [pbr::OriginalName("small")] Small = 0,
        [pbr::OriginalName("middle")] Middle = 1,
        [pbr::OriginalName("big")] Big = 2,
      }

    }
    #endregion

  }

  #endregion

}

#endregion Designer generated code
