// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: dwango/nicolive/chat/data/Gift.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Dwango.Nicolive.Chat.Data {

  /// <summary>Holder for reflection information generated from dwango/nicolive/chat/data/Gift.proto</summary>
  public static partial class GiftReflection {

    #region Descriptor
    /// <summary>File descriptor for dwango/nicolive/chat/data/Gift.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static GiftReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CiRkd2FuZ28vbmljb2xpdmUvY2hhdC9kYXRhL0dpZnQucHJvdG8SGWR3YW5n",
            "by5uaWNvbGl2ZS5jaGF0LmRhdGEimgEKBEdpZnQSDwoHaXRlbV9pZBgBIAEo",
            "CRIaChJhZHZlcnRpc2VyX3VzZXJfaWQYAiABKAMSFwoPYWR2ZXJ0aXNlcl9u",
            "YW1lGAMgASgJEg0KBXBvaW50GAQgASgDEg8KB21lc3NhZ2UYBSABKAkSEQoJ",
            "aXRlbV9uYW1lGAYgASgJEhkKEWNvbnRyaWJ1dGlvbl9yYW5rGAcgASgFYgZw",
            "cm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Dwango.Nicolive.Chat.Data.Gift), global::Dwango.Nicolive.Chat.Data.Gift.Parser, new[]{ "ItemId", "AdvertiserUserId", "AdvertiserName", "Point", "Message", "ItemName", "ContributionRank" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class Gift : pb::IMessage<Gift> {
    private static readonly pb::MessageParser<Gift> _parser = new pb::MessageParser<Gift>(() => new Gift());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Gift> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Dwango.Nicolive.Chat.Data.GiftReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Gift() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Gift(Gift other) : this() {
      itemId_ = other.itemId_;
      advertiserUserId_ = other.advertiserUserId_;
      advertiserName_ = other.advertiserName_;
      point_ = other.point_;
      message_ = other.message_;
      itemName_ = other.itemName_;
      contributionRank_ = other.contributionRank_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Gift Clone() {
      return new Gift(this);
    }

    /// <summary>Field number for the "item_id" field.</summary>
    public const int ItemIdFieldNumber = 1;
    private string itemId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string ItemId {
      get { return itemId_; }
      set {
        itemId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "advertiser_user_id" field.</summary>
    public const int AdvertiserUserIdFieldNumber = 2;
    private long advertiserUserId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long AdvertiserUserId {
      get { return advertiserUserId_; }
      set {
        advertiserUserId_ = value;
      }
    }

    /// <summary>Field number for the "advertiser_name" field.</summary>
    public const int AdvertiserNameFieldNumber = 3;
    private string advertiserName_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string AdvertiserName {
      get { return advertiserName_; }
      set {
        advertiserName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "point" field.</summary>
    public const int PointFieldNumber = 4;
    private long point_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long Point {
      get { return point_; }
      set {
        point_ = value;
      }
    }

    /// <summary>Field number for the "message" field.</summary>
    public const int MessageFieldNumber = 5;
    private string message_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Message {
      get { return message_; }
      set {
        message_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "item_name" field.</summary>
    public const int ItemNameFieldNumber = 6;
    private string itemName_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string ItemName {
      get { return itemName_; }
      set {
        itemName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "contribution_rank" field.</summary>
    public const int ContributionRankFieldNumber = 7;
    private int contributionRank_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int ContributionRank {
      get { return contributionRank_; }
      set {
        contributionRank_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Gift);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Gift other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (ItemId != other.ItemId) return false;
      if (AdvertiserUserId != other.AdvertiserUserId) return false;
      if (AdvertiserName != other.AdvertiserName) return false;
      if (Point != other.Point) return false;
      if (Message != other.Message) return false;
      if (ItemName != other.ItemName) return false;
      if (ContributionRank != other.ContributionRank) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (ItemId.Length != 0) hash ^= ItemId.GetHashCode();
      if (AdvertiserUserId != 0L) hash ^= AdvertiserUserId.GetHashCode();
      if (AdvertiserName.Length != 0) hash ^= AdvertiserName.GetHashCode();
      if (Point != 0L) hash ^= Point.GetHashCode();
      if (Message.Length != 0) hash ^= Message.GetHashCode();
      if (ItemName.Length != 0) hash ^= ItemName.GetHashCode();
      if (ContributionRank != 0) hash ^= ContributionRank.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (ItemId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(ItemId);
      }
      if (AdvertiserUserId != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(AdvertiserUserId);
      }
      if (AdvertiserName.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(AdvertiserName);
      }
      if (Point != 0L) {
        output.WriteRawTag(32);
        output.WriteInt64(Point);
      }
      if (Message.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(Message);
      }
      if (ItemName.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(ItemName);
      }
      if (ContributionRank != 0) {
        output.WriteRawTag(56);
        output.WriteInt32(ContributionRank);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (ItemId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ItemId);
      }
      if (AdvertiserUserId != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(AdvertiserUserId);
      }
      if (AdvertiserName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(AdvertiserName);
      }
      if (Point != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Point);
      }
      if (Message.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Message);
      }
      if (ItemName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ItemName);
      }
      if (ContributionRank != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(ContributionRank);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Gift other) {
      if (other == null) {
        return;
      }
      if (other.ItemId.Length != 0) {
        ItemId = other.ItemId;
      }
      if (other.AdvertiserUserId != 0L) {
        AdvertiserUserId = other.AdvertiserUserId;
      }
      if (other.AdvertiserName.Length != 0) {
        AdvertiserName = other.AdvertiserName;
      }
      if (other.Point != 0L) {
        Point = other.Point;
      }
      if (other.Message.Length != 0) {
        Message = other.Message;
      }
      if (other.ItemName.Length != 0) {
        ItemName = other.ItemName;
      }
      if (other.ContributionRank != 0) {
        ContributionRank = other.ContributionRank;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            ItemId = input.ReadString();
            break;
          }
          case 16: {
            AdvertiserUserId = input.ReadInt64();
            break;
          }
          case 26: {
            AdvertiserName = input.ReadString();
            break;
          }
          case 32: {
            Point = input.ReadInt64();
            break;
          }
          case 42: {
            Message = input.ReadString();
            break;
          }
          case 50: {
            ItemName = input.ReadString();
            break;
          }
          case 56: {
            ContributionRank = input.ReadInt32();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
