// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: dwango/nicolive/chat/service/edge/PackedSegment.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Dwango.Nicolive.Chat.Service.Edge {

  /// <summary>Holder for reflection information generated from dwango/nicolive/chat/service/edge/PackedSegment.proto</summary>
  public static partial class PackedSegmentReflection {

    #region Descriptor
    /// <summary>File descriptor for dwango/nicolive/chat/service/edge/PackedSegment.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static PackedSegmentReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CjVkd2FuZ28vbmljb2xpdmUvY2hhdC9zZXJ2aWNlL2VkZ2UvUGFja2VkU2Vn",
            "bWVudC5wcm90bxIhZHdhbmdvLm5pY29saXZlLmNoYXQuc2VydmljZS5lZGdl",
            "GjZkd2FuZ28vbmljb2xpdmUvY2hhdC9zZXJ2aWNlL2VkZ2UvQ2h1bmtlZE1l",
            "c3NhZ2UucHJvdG8ingIKDVBhY2tlZFNlZ21lbnQSQwoIbWVzc2FnZXMYASAD",
            "KAsyMS5kd2FuZ28ubmljb2xpdmUuY2hhdC5zZXJ2aWNlLmVkZ2UuQ2h1bmtl",
            "ZE1lc3NhZ2USQwoEbmV4dBgCIAEoCzI1LmR3YW5nby5uaWNvbGl2ZS5jaGF0",
            "LnNlcnZpY2UuZWRnZS5QYWNrZWRTZWdtZW50Lk5leHQSUAoIc25hcHNob3QY",
            "AyABKAsyPi5kd2FuZ28ubmljb2xpdmUuY2hhdC5zZXJ2aWNlLmVkZ2UuUGFj",
            "a2VkU2VnbWVudC5TdGF0ZVNuYXBzaG90GhMKBE5leHQSCwoDdXJpGAEgASgJ",
            "GhwKDVN0YXRlU25hcHNob3QSCwoDdXJpGAEgASgJYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Dwango.Nicolive.Chat.Service.Edge.ChunkedMessageReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Dwango.Nicolive.Chat.Service.Edge.PackedSegment), global::Dwango.Nicolive.Chat.Service.Edge.PackedSegment.Parser, new[]{ "Messages", "Next", "Snapshot" }, null, null, new pbr::GeneratedClrTypeInfo[] { new pbr::GeneratedClrTypeInfo(typeof(global::Dwango.Nicolive.Chat.Service.Edge.PackedSegment.Types.Next), global::Dwango.Nicolive.Chat.Service.Edge.PackedSegment.Types.Next.Parser, new[]{ "Uri" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Dwango.Nicolive.Chat.Service.Edge.PackedSegment.Types.StateSnapshot), global::Dwango.Nicolive.Chat.Service.Edge.PackedSegment.Types.StateSnapshot.Parser, new[]{ "Uri" }, null, null, null)})
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class PackedSegment : pb::IMessage<PackedSegment> {
    private static readonly pb::MessageParser<PackedSegment> _parser = new pb::MessageParser<PackedSegment>(() => new PackedSegment());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<PackedSegment> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Dwango.Nicolive.Chat.Service.Edge.PackedSegmentReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PackedSegment() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PackedSegment(PackedSegment other) : this() {
      messages_ = other.messages_.Clone();
      next_ = other.next_ != null ? other.next_.Clone() : null;
      snapshot_ = other.snapshot_ != null ? other.snapshot_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PackedSegment Clone() {
      return new PackedSegment(this);
    }

    /// <summary>Field number for the "messages" field.</summary>
    public const int MessagesFieldNumber = 1;
    private static readonly pb::FieldCodec<global::Dwango.Nicolive.Chat.Service.Edge.ChunkedMessage> _repeated_messages_codec
        = pb::FieldCodec.ForMessage(10, global::Dwango.Nicolive.Chat.Service.Edge.ChunkedMessage.Parser);
    private readonly pbc::RepeatedField<global::Dwango.Nicolive.Chat.Service.Edge.ChunkedMessage> messages_ = new pbc::RepeatedField<global::Dwango.Nicolive.Chat.Service.Edge.ChunkedMessage>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::Dwango.Nicolive.Chat.Service.Edge.ChunkedMessage> Messages {
      get { return messages_; }
    }

    /// <summary>Field number for the "next" field.</summary>
    public const int NextFieldNumber = 2;
    private global::Dwango.Nicolive.Chat.Service.Edge.PackedSegment.Types.Next next_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Dwango.Nicolive.Chat.Service.Edge.PackedSegment.Types.Next Next {
      get { return next_; }
      set {
        next_ = value;
      }
    }

    /// <summary>Field number for the "snapshot" field.</summary>
    public const int SnapshotFieldNumber = 3;
    private global::Dwango.Nicolive.Chat.Service.Edge.PackedSegment.Types.StateSnapshot snapshot_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Dwango.Nicolive.Chat.Service.Edge.PackedSegment.Types.StateSnapshot Snapshot {
      get { return snapshot_; }
      set {
        snapshot_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as PackedSegment);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(PackedSegment other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!messages_.Equals(other.messages_)) return false;
      if (!object.Equals(Next, other.Next)) return false;
      if (!object.Equals(Snapshot, other.Snapshot)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= messages_.GetHashCode();
      if (next_ != null) hash ^= Next.GetHashCode();
      if (snapshot_ != null) hash ^= Snapshot.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      messages_.WriteTo(output, _repeated_messages_codec);
      if (next_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Next);
      }
      if (snapshot_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(Snapshot);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      size += messages_.CalculateSize(_repeated_messages_codec);
      if (next_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Next);
      }
      if (snapshot_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Snapshot);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(PackedSegment other) {
      if (other == null) {
        return;
      }
      messages_.Add(other.messages_);
      if (other.next_ != null) {
        if (next_ == null) {
          next_ = new global::Dwango.Nicolive.Chat.Service.Edge.PackedSegment.Types.Next();
        }
        Next.MergeFrom(other.Next);
      }
      if (other.snapshot_ != null) {
        if (snapshot_ == null) {
          snapshot_ = new global::Dwango.Nicolive.Chat.Service.Edge.PackedSegment.Types.StateSnapshot();
        }
        Snapshot.MergeFrom(other.Snapshot);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            messages_.AddEntriesFrom(input, _repeated_messages_codec);
            break;
          }
          case 18: {
            if (next_ == null) {
              next_ = new global::Dwango.Nicolive.Chat.Service.Edge.PackedSegment.Types.Next();
            }
            input.ReadMessage(next_);
            break;
          }
          case 26: {
            if (snapshot_ == null) {
              snapshot_ = new global::Dwango.Nicolive.Chat.Service.Edge.PackedSegment.Types.StateSnapshot();
            }
            input.ReadMessage(snapshot_);
            break;
          }
        }
      }
    }

    #region Nested types
    /// <summary>Container for nested types declared in the PackedSegment message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static partial class Types {
      public sealed partial class Next : pb::IMessage<Next> {
        private static readonly pb::MessageParser<Next> _parser = new pb::MessageParser<Next>(() => new Next());
        private pb::UnknownFieldSet _unknownFields;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public static pb::MessageParser<Next> Parser { get { return _parser; } }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public static pbr::MessageDescriptor Descriptor {
          get { return global::Dwango.Nicolive.Chat.Service.Edge.PackedSegment.Descriptor.NestedTypes[0]; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        pbr::MessageDescriptor pb::IMessage.Descriptor {
          get { return Descriptor; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public Next() {
          OnConstruction();
        }

        partial void OnConstruction();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public Next(Next other) : this() {
          uri_ = other.uri_;
          _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public Next Clone() {
          return new Next(this);
        }

        /// <summary>Field number for the "uri" field.</summary>
        public const int UriFieldNumber = 1;
        private string uri_ = "";
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public string Uri {
          get { return uri_; }
          set {
            uri_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
          }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override bool Equals(object other) {
          return Equals(other as Next);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public bool Equals(Next other) {
          if (ReferenceEquals(other, null)) {
            return false;
          }
          if (ReferenceEquals(other, this)) {
            return true;
          }
          if (Uri != other.Uri) return false;
          return Equals(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override int GetHashCode() {
          int hash = 1;
          if (Uri.Length != 0) hash ^= Uri.GetHashCode();
          if (_unknownFields != null) {
            hash ^= _unknownFields.GetHashCode();
          }
          return hash;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override string ToString() {
          return pb::JsonFormatter.ToDiagnosticString(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void WriteTo(pb::CodedOutputStream output) {
          if (Uri.Length != 0) {
            output.WriteRawTag(10);
            output.WriteString(Uri);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(output);
          }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public int CalculateSize() {
          int size = 0;
          if (Uri.Length != 0) {
            size += 1 + pb::CodedOutputStream.ComputeStringSize(Uri);
          }
          if (_unknownFields != null) {
            size += _unknownFields.CalculateSize();
          }
          return size;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void MergeFrom(Next other) {
          if (other == null) {
            return;
          }
          if (other.Uri.Length != 0) {
            Uri = other.Uri;
          }
          _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void MergeFrom(pb::CodedInputStream input) {
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
            switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                break;
              case 10: {
                Uri = input.ReadString();
                break;
              }
            }
          }
        }

      }

      public sealed partial class StateSnapshot : pb::IMessage<StateSnapshot> {
        private static readonly pb::MessageParser<StateSnapshot> _parser = new pb::MessageParser<StateSnapshot>(() => new StateSnapshot());
        private pb::UnknownFieldSet _unknownFields;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public static pb::MessageParser<StateSnapshot> Parser { get { return _parser; } }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public static pbr::MessageDescriptor Descriptor {
          get { return global::Dwango.Nicolive.Chat.Service.Edge.PackedSegment.Descriptor.NestedTypes[1]; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        pbr::MessageDescriptor pb::IMessage.Descriptor {
          get { return Descriptor; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public StateSnapshot() {
          OnConstruction();
        }

        partial void OnConstruction();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public StateSnapshot(StateSnapshot other) : this() {
          uri_ = other.uri_;
          _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public StateSnapshot Clone() {
          return new StateSnapshot(this);
        }

        /// <summary>Field number for the "uri" field.</summary>
        public const int UriFieldNumber = 1;
        private string uri_ = "";
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public string Uri {
          get { return uri_; }
          set {
            uri_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
          }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override bool Equals(object other) {
          return Equals(other as StateSnapshot);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public bool Equals(StateSnapshot other) {
          if (ReferenceEquals(other, null)) {
            return false;
          }
          if (ReferenceEquals(other, this)) {
            return true;
          }
          if (Uri != other.Uri) return false;
          return Equals(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override int GetHashCode() {
          int hash = 1;
          if (Uri.Length != 0) hash ^= Uri.GetHashCode();
          if (_unknownFields != null) {
            hash ^= _unknownFields.GetHashCode();
          }
          return hash;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override string ToString() {
          return pb::JsonFormatter.ToDiagnosticString(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void WriteTo(pb::CodedOutputStream output) {
          if (Uri.Length != 0) {
            output.WriteRawTag(10);
            output.WriteString(Uri);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(output);
          }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public int CalculateSize() {
          int size = 0;
          if (Uri.Length != 0) {
            size += 1 + pb::CodedOutputStream.ComputeStringSize(Uri);
          }
          if (_unknownFields != null) {
            size += _unknownFields.CalculateSize();
          }
          return size;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void MergeFrom(StateSnapshot other) {
          if (other == null) {
            return;
          }
          if (other.Uri.Length != 0) {
            Uri = other.Uri;
          }
          _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void MergeFrom(pb::CodedInputStream input) {
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
            switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                break;
              case 10: {
                Uri = input.ReadString();
                break;
              }
            }
          }
        }

      }

    }
    #endregion

  }

  #endregion

}

#endregion Designer generated code
