// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: dwango/nicolive/chat/data/SimpleNotification.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Dwango.Nicolive.Chat.Data {

  /// <summary>Holder for reflection information generated from dwango/nicolive/chat/data/SimpleNotification.proto</summary>
  public static partial class SimpleNotificationReflection {

    #region Descriptor
    /// <summary>File descriptor for dwango/nicolive/chat/data/SimpleNotification.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static SimpleNotificationReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CjJkd2FuZ28vbmljb2xpdmUvY2hhdC9kYXRhL1NpbXBsZU5vdGlmaWNhdGlv",
            "bi5wcm90bxIZZHdhbmdvLm5pY29saXZlLmNoYXQuZGF0YRoeZ29vZ2xlL3By",
            "b3RvYnVmL2R1cmF0aW9uLnByb3RvIscBChJTaW1wbGVOb3RpZmljYXRpb24S",
            "EAoGaWNoaWJhGAEgASgJSAASDwoFcXVvdGUYAiABKAlIABIRCgdlbW90aW9u",
            "GAMgASgJSAASEAoGY3J1aXNlGAQgASgJSAASGgoQcHJvZ3JhbV9leHRlbmRl",
            "ZBgFIAEoCUgAEhQKCnJhbmtpbmdfaW4YBiABKAlIABIZCg9yYW5raW5nX3Vw",
            "ZGF0ZWQYCCABKAlIABIRCgd2aXNpdGVkGAcgASgJSABCCQoHbWVzc2FnZWIG",
            "cHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Google.Protobuf.WellKnownTypes.DurationReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Dwango.Nicolive.Chat.Data.SimpleNotification), global::Dwango.Nicolive.Chat.Data.SimpleNotification.Parser, new[]{ "Ichiba", "Quote", "Emotion", "Cruise", "ProgramExtended", "RankingIn", "RankingUpdated", "Visited" }, new[]{ "Message" }, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class SimpleNotification : pb::IMessage<SimpleNotification> {
    private static readonly pb::MessageParser<SimpleNotification> _parser = new pb::MessageParser<SimpleNotification>(() => new SimpleNotification());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<SimpleNotification> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Dwango.Nicolive.Chat.Data.SimpleNotificationReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SimpleNotification() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SimpleNotification(SimpleNotification other) : this() {
      switch (other.MessageCase) {
        case MessageOneofCase.Ichiba:
          Ichiba = other.Ichiba;
          break;
        case MessageOneofCase.Quote:
          Quote = other.Quote;
          break;
        case MessageOneofCase.Emotion:
          Emotion = other.Emotion;
          break;
        case MessageOneofCase.Cruise:
          Cruise = other.Cruise;
          break;
        case MessageOneofCase.ProgramExtended:
          ProgramExtended = other.ProgramExtended;
          break;
        case MessageOneofCase.RankingIn:
          RankingIn = other.RankingIn;
          break;
        case MessageOneofCase.RankingUpdated:
          RankingUpdated = other.RankingUpdated;
          break;
        case MessageOneofCase.Visited:
          Visited = other.Visited;
          break;
      }

      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SimpleNotification Clone() {
      return new SimpleNotification(this);
    }

    /// <summary>Field number for the "ichiba" field.</summary>
    public const int IchibaFieldNumber = 1;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Ichiba {
      get { return messageCase_ == MessageOneofCase.Ichiba ? (string) message_ : ""; }
      set {
        message_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
        messageCase_ = MessageOneofCase.Ichiba;
      }
    }

    /// <summary>Field number for the "quote" field.</summary>
    public const int QuoteFieldNumber = 2;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Quote {
      get { return messageCase_ == MessageOneofCase.Quote ? (string) message_ : ""; }
      set {
        message_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
        messageCase_ = MessageOneofCase.Quote;
      }
    }

    /// <summary>Field number for the "emotion" field.</summary>
    public const int EmotionFieldNumber = 3;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Emotion {
      get { return messageCase_ == MessageOneofCase.Emotion ? (string) message_ : ""; }
      set {
        message_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
        messageCase_ = MessageOneofCase.Emotion;
      }
    }

    /// <summary>Field number for the "cruise" field.</summary>
    public const int CruiseFieldNumber = 4;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Cruise {
      get { return messageCase_ == MessageOneofCase.Cruise ? (string) message_ : ""; }
      set {
        message_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
        messageCase_ = MessageOneofCase.Cruise;
      }
    }

    /// <summary>Field number for the "program_extended" field.</summary>
    public const int ProgramExtendedFieldNumber = 5;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string ProgramExtended {
      get { return messageCase_ == MessageOneofCase.ProgramExtended ? (string) message_ : ""; }
      set {
        message_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
        messageCase_ = MessageOneofCase.ProgramExtended;
      }
    }

    /// <summary>Field number for the "ranking_in" field.</summary>
    public const int RankingInFieldNumber = 6;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string RankingIn {
      get { return messageCase_ == MessageOneofCase.RankingIn ? (string) message_ : ""; }
      set {
        message_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
        messageCase_ = MessageOneofCase.RankingIn;
      }
    }

    /// <summary>Field number for the "ranking_updated" field.</summary>
    public const int RankingUpdatedFieldNumber = 8;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string RankingUpdated {
      get { return messageCase_ == MessageOneofCase.RankingUpdated ? (string) message_ : ""; }
      set {
        message_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
        messageCase_ = MessageOneofCase.RankingUpdated;
      }
    }

    /// <summary>Field number for the "visited" field.</summary>
    public const int VisitedFieldNumber = 7;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Visited {
      get { return messageCase_ == MessageOneofCase.Visited ? (string) message_ : ""; }
      set {
        message_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
        messageCase_ = MessageOneofCase.Visited;
      }
    }

    private object message_;
    /// <summary>Enum of possible cases for the "message" oneof.</summary>
    public enum MessageOneofCase {
      None = 0,
      Ichiba = 1,
      Quote = 2,
      Emotion = 3,
      Cruise = 4,
      ProgramExtended = 5,
      RankingIn = 6,
      RankingUpdated = 8,
      Visited = 7,
    }
    private MessageOneofCase messageCase_ = MessageOneofCase.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public MessageOneofCase MessageCase {
      get { return messageCase_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearMessage() {
      messageCase_ = MessageOneofCase.None;
      message_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as SimpleNotification);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(SimpleNotification other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Ichiba != other.Ichiba) return false;
      if (Quote != other.Quote) return false;
      if (Emotion != other.Emotion) return false;
      if (Cruise != other.Cruise) return false;
      if (ProgramExtended != other.ProgramExtended) return false;
      if (RankingIn != other.RankingIn) return false;
      if (RankingUpdated != other.RankingUpdated) return false;
      if (Visited != other.Visited) return false;
      if (MessageCase != other.MessageCase) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (messageCase_ == MessageOneofCase.Ichiba) hash ^= Ichiba.GetHashCode();
      if (messageCase_ == MessageOneofCase.Quote) hash ^= Quote.GetHashCode();
      if (messageCase_ == MessageOneofCase.Emotion) hash ^= Emotion.GetHashCode();
      if (messageCase_ == MessageOneofCase.Cruise) hash ^= Cruise.GetHashCode();
      if (messageCase_ == MessageOneofCase.ProgramExtended) hash ^= ProgramExtended.GetHashCode();
      if (messageCase_ == MessageOneofCase.RankingIn) hash ^= RankingIn.GetHashCode();
      if (messageCase_ == MessageOneofCase.RankingUpdated) hash ^= RankingUpdated.GetHashCode();
      if (messageCase_ == MessageOneofCase.Visited) hash ^= Visited.GetHashCode();
      hash ^= (int) messageCase_;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (messageCase_ == MessageOneofCase.Ichiba) {
        output.WriteRawTag(10);
        output.WriteString(Ichiba);
      }
      if (messageCase_ == MessageOneofCase.Quote) {
        output.WriteRawTag(18);
        output.WriteString(Quote);
      }
      if (messageCase_ == MessageOneofCase.Emotion) {
        output.WriteRawTag(26);
        output.WriteString(Emotion);
      }
      if (messageCase_ == MessageOneofCase.Cruise) {
        output.WriteRawTag(34);
        output.WriteString(Cruise);
      }
      if (messageCase_ == MessageOneofCase.ProgramExtended) {
        output.WriteRawTag(42);
        output.WriteString(ProgramExtended);
      }
      if (messageCase_ == MessageOneofCase.RankingIn) {
        output.WriteRawTag(50);
        output.WriteString(RankingIn);
      }
      if (messageCase_ == MessageOneofCase.Visited) {
        output.WriteRawTag(58);
        output.WriteString(Visited);
      }
      if (messageCase_ == MessageOneofCase.RankingUpdated) {
        output.WriteRawTag(66);
        output.WriteString(RankingUpdated);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (messageCase_ == MessageOneofCase.Ichiba) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Ichiba);
      }
      if (messageCase_ == MessageOneofCase.Quote) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Quote);
      }
      if (messageCase_ == MessageOneofCase.Emotion) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Emotion);
      }
      if (messageCase_ == MessageOneofCase.Cruise) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Cruise);
      }
      if (messageCase_ == MessageOneofCase.ProgramExtended) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ProgramExtended);
      }
      if (messageCase_ == MessageOneofCase.RankingIn) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(RankingIn);
      }
      if (messageCase_ == MessageOneofCase.RankingUpdated) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(RankingUpdated);
      }
      if (messageCase_ == MessageOneofCase.Visited) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Visited);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(SimpleNotification other) {
      if (other == null) {
        return;
      }
      switch (other.MessageCase) {
        case MessageOneofCase.Ichiba:
          Ichiba = other.Ichiba;
          break;
        case MessageOneofCase.Quote:
          Quote = other.Quote;
          break;
        case MessageOneofCase.Emotion:
          Emotion = other.Emotion;
          break;
        case MessageOneofCase.Cruise:
          Cruise = other.Cruise;
          break;
        case MessageOneofCase.ProgramExtended:
          ProgramExtended = other.ProgramExtended;
          break;
        case MessageOneofCase.RankingIn:
          RankingIn = other.RankingIn;
          break;
        case MessageOneofCase.RankingUpdated:
          RankingUpdated = other.RankingUpdated;
          break;
        case MessageOneofCase.Visited:
          Visited = other.Visited;
          break;
      }

      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Ichiba = input.ReadString();
            break;
          }
          case 18: {
            Quote = input.ReadString();
            break;
          }
          case 26: {
            Emotion = input.ReadString();
            break;
          }
          case 34: {
            Cruise = input.ReadString();
            break;
          }
          case 42: {
            ProgramExtended = input.ReadString();
            break;
          }
          case 50: {
            RankingIn = input.ReadString();
            break;
          }
          case 58: {
            Visited = input.ReadString();
            break;
          }
          case 66: {
            RankingUpdated = input.ReadString();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
