// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: dwango/nicolive/chat/data/atoms/SSNGUpdated.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Dwango.Nicolive.Chat.Data.Atoms {

  /// <summary>Holder for reflection information generated from dwango/nicolive/chat/data/atoms/SSNGUpdated.proto</summary>
  public static partial class SSNGUpdatedReflection {

    #region Descriptor
    /// <summary>File descriptor for dwango/nicolive/chat/data/atoms/SSNGUpdated.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static SSNGUpdatedReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CjFkd2FuZ28vbmljb2xpdmUvY2hhdC9kYXRhL2F0b21zL1NTTkdVcGRhdGVk",
            "LnByb3RvEh9kd2FuZ28ubmljb2xpdmUuY2hhdC5kYXRhLmF0b21zGh9nb29n",
            "bGUvcHJvdG9idWYvdGltZXN0YW1wLnByb3RvGjdkd2FuZ28vbmljb2xpdmUv",
            "Y2hhdC9kYXRhL2F0b21zL01vZGVyYXRvclVzZXJJbmZvLnByb3RvIooDCgtT",
            "U05HVXBkYXRlZBJNCglvcGVyYXRpb24YASABKA4yOi5kd2FuZ28ubmljb2xp",
            "dmUuY2hhdC5kYXRhLmF0b21zLlNTTkdVcGRhdGVkLlNTTkdPcGVyYXRpb24S",
            "DwoHc3NuZ19pZBgCIAEoAxJECghvcGVyYXRvchgDIAEoCzIyLmR3YW5nby5u",
            "aWNvbGl2ZS5jaGF0LmRhdGEuYXRvbXMuTW9kZXJhdG9yVXNlckluZm8SQwoE",
            "dHlwZRgEIAEoDjI1LmR3YW5nby5uaWNvbGl2ZS5jaGF0LmRhdGEuYXRvbXMu",
            "U1NOR1VwZGF0ZWQuU1NOR1R5cGUSDgoGc291cmNlGAUgASgJEi0KCXVwZGF0",
            "ZWRBdBgGIAEoCzIaLmdvb2dsZS5wcm90b2J1Zi5UaW1lc3RhbXAiJAoNU1NO",
            "R09wZXJhdGlvbhIHCgNBREQQABIKCgZERUxFVEUQASIrCghTU05HVHlwZRII",
            "CgRVU0VSEAASCAoEV09SRBABEgsKB0NPTU1BTkQQAmIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Google.Protobuf.WellKnownTypes.TimestampReflection.Descriptor, global::Dwango.Nicolive.Chat.Data.Atoms.ModeratorUserInfoReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Dwango.Nicolive.Chat.Data.Atoms.SSNGUpdated), global::Dwango.Nicolive.Chat.Data.Atoms.SSNGUpdated.Parser, new[]{ "Operation", "SsngId", "Operator", "Type", "Source", "UpdatedAt" }, null, new[]{ typeof(global::Dwango.Nicolive.Chat.Data.Atoms.SSNGUpdated.Types.SSNGOperation), typeof(global::Dwango.Nicolive.Chat.Data.Atoms.SSNGUpdated.Types.SSNGType) }, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class SSNGUpdated : pb::IMessage<SSNGUpdated> {
    private static readonly pb::MessageParser<SSNGUpdated> _parser = new pb::MessageParser<SSNGUpdated>(() => new SSNGUpdated());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<SSNGUpdated> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Dwango.Nicolive.Chat.Data.Atoms.SSNGUpdatedReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SSNGUpdated() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SSNGUpdated(SSNGUpdated other) : this() {
      operation_ = other.operation_;
      ssngId_ = other.ssngId_;
      operator_ = other.operator_ != null ? other.operator_.Clone() : null;
      type_ = other.type_;
      source_ = other.source_;
      updatedAt_ = other.updatedAt_ != null ? other.updatedAt_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SSNGUpdated Clone() {
      return new SSNGUpdated(this);
    }

    /// <summary>Field number for the "operation" field.</summary>
    public const int OperationFieldNumber = 1;
    private global::Dwango.Nicolive.Chat.Data.Atoms.SSNGUpdated.Types.SSNGOperation operation_ = 0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Dwango.Nicolive.Chat.Data.Atoms.SSNGUpdated.Types.SSNGOperation Operation {
      get { return operation_; }
      set {
        operation_ = value;
      }
    }

    /// <summary>Field number for the "ssng_id" field.</summary>
    public const int SsngIdFieldNumber = 2;
    private long ssngId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long SsngId {
      get { return ssngId_; }
      set {
        ssngId_ = value;
      }
    }

    /// <summary>Field number for the "operator" field.</summary>
    public const int OperatorFieldNumber = 3;
    private global::Dwango.Nicolive.Chat.Data.Atoms.ModeratorUserInfo operator_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Dwango.Nicolive.Chat.Data.Atoms.ModeratorUserInfo Operator {
      get { return operator_; }
      set {
        operator_ = value;
      }
    }

    /// <summary>Field number for the "type" field.</summary>
    public const int TypeFieldNumber = 4;
    private global::Dwango.Nicolive.Chat.Data.Atoms.SSNGUpdated.Types.SSNGType type_ = 0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Dwango.Nicolive.Chat.Data.Atoms.SSNGUpdated.Types.SSNGType Type {
      get { return type_; }
      set {
        type_ = value;
      }
    }

    /// <summary>Field number for the "source" field.</summary>
    public const int SourceFieldNumber = 5;
    private string source_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Source {
      get { return source_; }
      set {
        source_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "updatedAt" field.</summary>
    public const int UpdatedAtFieldNumber = 6;
    private global::Google.Protobuf.WellKnownTypes.Timestamp updatedAt_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Google.Protobuf.WellKnownTypes.Timestamp UpdatedAt {
      get { return updatedAt_; }
      set {
        updatedAt_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as SSNGUpdated);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(SSNGUpdated other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Operation != other.Operation) return false;
      if (SsngId != other.SsngId) return false;
      if (!object.Equals(Operator, other.Operator)) return false;
      if (Type != other.Type) return false;
      if (Source != other.Source) return false;
      if (!object.Equals(UpdatedAt, other.UpdatedAt)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Operation != 0) hash ^= Operation.GetHashCode();
      if (SsngId != 0L) hash ^= SsngId.GetHashCode();
      if (operator_ != null) hash ^= Operator.GetHashCode();
      if (Type != 0) hash ^= Type.GetHashCode();
      if (Source.Length != 0) hash ^= Source.GetHashCode();
      if (updatedAt_ != null) hash ^= UpdatedAt.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Operation != 0) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Operation);
      }
      if (SsngId != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(SsngId);
      }
      if (operator_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(Operator);
      }
      if (Type != 0) {
        output.WriteRawTag(32);
        output.WriteEnum((int) Type);
      }
      if (Source.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(Source);
      }
      if (updatedAt_ != null) {
        output.WriteRawTag(50);
        output.WriteMessage(UpdatedAt);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Operation != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Operation);
      }
      if (SsngId != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(SsngId);
      }
      if (operator_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Operator);
      }
      if (Type != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Type);
      }
      if (Source.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Source);
      }
      if (updatedAt_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(UpdatedAt);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(SSNGUpdated other) {
      if (other == null) {
        return;
      }
      if (other.Operation != 0) {
        Operation = other.Operation;
      }
      if (other.SsngId != 0L) {
        SsngId = other.SsngId;
      }
      if (other.operator_ != null) {
        if (operator_ == null) {
          operator_ = new global::Dwango.Nicolive.Chat.Data.Atoms.ModeratorUserInfo();
        }
        Operator.MergeFrom(other.Operator);
      }
      if (other.Type != 0) {
        Type = other.Type;
      }
      if (other.Source.Length != 0) {
        Source = other.Source;
      }
      if (other.updatedAt_ != null) {
        if (updatedAt_ == null) {
          updatedAt_ = new global::Google.Protobuf.WellKnownTypes.Timestamp();
        }
        UpdatedAt.MergeFrom(other.UpdatedAt);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            operation_ = (global::Dwango.Nicolive.Chat.Data.Atoms.SSNGUpdated.Types.SSNGOperation) input.ReadEnum();
            break;
          }
          case 16: {
            SsngId = input.ReadInt64();
            break;
          }
          case 26: {
            if (operator_ == null) {
              operator_ = new global::Dwango.Nicolive.Chat.Data.Atoms.ModeratorUserInfo();
            }
            input.ReadMessage(operator_);
            break;
          }
          case 32: {
            type_ = (global::Dwango.Nicolive.Chat.Data.Atoms.SSNGUpdated.Types.SSNGType) input.ReadEnum();
            break;
          }
          case 42: {
            Source = input.ReadString();
            break;
          }
          case 50: {
            if (updatedAt_ == null) {
              updatedAt_ = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(updatedAt_);
            break;
          }
        }
      }
    }

    #region Nested types
    /// <summary>Container for nested types declared in the SSNGUpdated message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static partial class Types {
      public enum SSNGOperation {
        [pbr::OriginalName("ADD")] Add = 0,
        [pbr::OriginalName("DELETE")] Delete = 1,
      }

      public enum SSNGType {
        [pbr::OriginalName("USER")] User = 0,
        [pbr::OriginalName("WORD")] Word = 1,
        [pbr::OriginalName("COMMAND")] Command = 2,
      }

    }
    #endregion

  }

  #endregion

}

#endregion Designer generated code
