// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: dwango/nicolive/chat/data/TrialPanel.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Dwango.Nicolive.Chat.Data {

  /// <summary>Holder for reflection information generated from dwango/nicolive/chat/data/TrialPanel.proto</summary>
  public static partial class TrialPanelReflection {

    #region Descriptor
    /// <summary>File descriptor for dwango/nicolive/chat/data/TrialPanel.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static TrialPanelReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cipkd2FuZ28vbmljb2xpdmUvY2hhdC9kYXRhL1RyaWFsUGFuZWwucHJvdG8S",
            "GWR3YW5nby5uaWNvbGl2ZS5jaGF0LmRhdGEi5AEKClRyaWFsUGFuZWwSOgoF",
            "cGFuZWwYASABKA4yKy5kd2FuZ28ubmljb2xpdmUuY2hhdC5kYXRhLlRyaWFs",
            "UGFuZWwuUGFuZWwSRAoQdW5xdWFsaWZpZWRfdXNlchgCIAEoDjIqLmR3YW5n",
            "by5uaWNvbGl2ZS5jaGF0LmRhdGEuVHJpYWxQYW5lbC5Nb2RlIiAKBVBhbmVs",
            "EgoKBkhpZGRlbhAAEgsKB0Rpc3BsYXkQASIyCgRNb2RlEgsKB0FsbG93ZWQQ",
            "ABIOCgpSZXN0cmljdGVkEAESDQoJRm9yYmlkZGVuEAJiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Dwango.Nicolive.Chat.Data.TrialPanel), global::Dwango.Nicolive.Chat.Data.TrialPanel.Parser, new[]{ "Panel", "UnqualifiedUser" }, null, new[]{ typeof(global::Dwango.Nicolive.Chat.Data.TrialPanel.Types.Panel), typeof(global::Dwango.Nicolive.Chat.Data.TrialPanel.Types.Mode) }, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class TrialPanel : pb::IMessage<TrialPanel> {
    private static readonly pb::MessageParser<TrialPanel> _parser = new pb::MessageParser<TrialPanel>(() => new TrialPanel());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<TrialPanel> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Dwango.Nicolive.Chat.Data.TrialPanelReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public TrialPanel() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public TrialPanel(TrialPanel other) : this() {
      panel_ = other.panel_;
      unqualifiedUser_ = other.unqualifiedUser_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public TrialPanel Clone() {
      return new TrialPanel(this);
    }

    /// <summary>Field number for the "panel" field.</summary>
    public const int PanelFieldNumber = 1;
    private global::Dwango.Nicolive.Chat.Data.TrialPanel.Types.Panel panel_ = 0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Dwango.Nicolive.Chat.Data.TrialPanel.Types.Panel Panel {
      get { return panel_; }
      set {
        panel_ = value;
      }
    }

    /// <summary>Field number for the "unqualified_user" field.</summary>
    public const int UnqualifiedUserFieldNumber = 2;
    private global::Dwango.Nicolive.Chat.Data.TrialPanel.Types.Mode unqualifiedUser_ = 0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Dwango.Nicolive.Chat.Data.TrialPanel.Types.Mode UnqualifiedUser {
      get { return unqualifiedUser_; }
      set {
        unqualifiedUser_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as TrialPanel);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(TrialPanel other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Panel != other.Panel) return false;
      if (UnqualifiedUser != other.UnqualifiedUser) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Panel != 0) hash ^= Panel.GetHashCode();
      if (UnqualifiedUser != 0) hash ^= UnqualifiedUser.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Panel != 0) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Panel);
      }
      if (UnqualifiedUser != 0) {
        output.WriteRawTag(16);
        output.WriteEnum((int) UnqualifiedUser);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Panel != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Panel);
      }
      if (UnqualifiedUser != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) UnqualifiedUser);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(TrialPanel other) {
      if (other == null) {
        return;
      }
      if (other.Panel != 0) {
        Panel = other.Panel;
      }
      if (other.UnqualifiedUser != 0) {
        UnqualifiedUser = other.UnqualifiedUser;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            panel_ = (global::Dwango.Nicolive.Chat.Data.TrialPanel.Types.Panel) input.ReadEnum();
            break;
          }
          case 16: {
            unqualifiedUser_ = (global::Dwango.Nicolive.Chat.Data.TrialPanel.Types.Mode) input.ReadEnum();
            break;
          }
        }
      }
    }

    #region Nested types
    /// <summary>Container for nested types declared in the TrialPanel message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static partial class Types {
      public enum Panel {
        [pbr::OriginalName("Hidden")] Hidden = 0,
        [pbr::OriginalName("Display")] Display = 1,
      }

      public enum Mode {
        [pbr::OriginalName("Allowed")] Allowed = 0,
        [pbr::OriginalName("Restricted")] Restricted = 1,
        [pbr::OriginalName("Forbidden")] Forbidden = 2,
      }

    }
    #endregion

  }

  #endregion

}

#endregion Designer generated code
