name: .NET Desktop App Build

on:
  workflow_dispatch:
    inputs:
      tagname:
        description: 'tagname'
        required: true
        default: '0.6.35'
jobs:
  build:
    runs-on: windows-latest

    env:
      Configuration: Release
      Output_Directory: build_output         # ビルド成果物を出力するディレクトリ名

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: true
        recursive: true

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.x'  # 使用する .NET のバージョンを指定

    - name: Restore dependencies
      run: dotnet restore $env:Solution_Name

    - name: Build solution
      run: dotnet build ./MultiCommentViewer/MultiCommentViewer.csproj --configuration $env:Configuration

    - name: Archive Release
      uses: thedoctor0/zip-release@0.7.5
      with:
        type: 'zip'
        filename: 'MultiCommentViewer_v${{ github.event.inputs.tagname }}_stable.zip'
        directory: ./Output/Release

    - name: Upload Release
      uses: ncipollo/release-action@v1.12.0
      with:
        artifacts: 'MultiCommentViewer_v${{ github.event.inputs.tagname }}_stable.zip'
        tag: ${{ github.event.inputs.tagname }}
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Publish artifacts
      uses: actions/upload-artifact@v3
      with:
        name: DesktopApp
        path: 'MultiCommentViewer_v${{ github.event.inputs.tagname }}_stable.zip'
