name: .NET Desktop App Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-latest

    env:
      Configuration: Release
      Output_Directory: build_output         # ビルド成果物を出力するディレクトリ名

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: true
        recursive: true

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.x'  # 使用する .NET のバージョンを指定

    - name: Restore dependencies
      run: dotnet restore $env:Solution_Name

    - name: Build solution
      run: dotnet build ./MultiCommentViewer/MultiCommentViewer.csproj --configuration $env:Configuration

    - name: Publish artifacts
      uses: actions/upload-artifact@v3
      with:
        name: DesktopApp
        path: ./Output
