name: .NET Desktop App Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-latest

    env:
      Configuration: Release
      Solution_Name: MultiCommentViewer.sln  # 置き換え: あなたのソリューションファイル名
      Output_Directory: build_output         # ビルド成果物を出力するディレクトリ名

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.x'  # 使用する .NET のバージョンを指定

    - name: Restore dependencies
      run: dotnet restore $env:Solution_Name

    - name: Build solution
      run: dotnet build $env:Solution_Name --configuration $env:Configuration --output $env:Output_Directory

    - name: Publish artifacts
      uses: actions/upload-artifact@v3
      with:
        name: DesktopApp
        path: ${{ env.Output_Directory }}
